### PR TITLE
Correctly support different Cortex-M architectures

### PR DESCRIPTION
**Pull request by maximevince**
Simple defines to allow this awesome code to compile for Cortex-m0, too.

### CODE REVIEW

**Comment by stg** [comment]
Would be great if there was a define that reliably identifies whether the DSP instructions are available.
As far as I know, DSP instructions start at Cortex M4, so the check might need to be __CORTEX_M > 3 or what do you say?
There should also be a #warning issued that DSP instructions are not being used and that performance may suffer, especially if the define is missing for some reason when compiling for a DSP capable ARM.

**Comment by maximevince** [comment]
Sounds like a better plan indeed. I believe there is a DSP define in the
CMSIS standard, so I will rework the pull request and issue a #warning, too!

**Comment by stg** [comment]
You're awesome!
I never considered other ARM targets and the non-DSP fallback was designed for testing and conformancy on PC. Are you still getting decent performance? Have you compared with anything?

**Comment by maximevince** [comment]
I started on an cortex-m0 target @ 16 mhz with the CMSIS DSP libraries.
Their example uses a 1024-sample complex float dataset. (with all i-values == 0)
This took ~330 ms on the m0 to process.

But since an integer-only FFT would perform much better on the DSP-less m0,
this is probably not a fair comparison.

How would you translate the complex float dataset to an integer set for your FFT functions?
Would "fft_phase_magnitude()" work?

**Comment by maximevince** [comment]
Ok, pull request updated!

Turns out there were "__FPU_PRESENT" and "__FPU_USED",
but there instructions are not FPU instructions, but rather instructions present in the ARMv7-M (M3) or ARMv7E-M (M4, M7) architecture. The Cortex-M0 is using the ARMv6-M achitecture, lacking most of these advanced instructions.
I have updated the defines to detect all cases correctly.
Prerequisite is or course to use a CMSIS CPU header, which has these defines set correctly.

**Comment by stg** [comment]
A fair comparison would be to use integer 32 bit on each library.

Are you doing forward (signal to frequencies) or inverse (frequencies to signal) FFT?

The functions fft_phase_magnitude, fft_magnitude, fft_real_dc, fft_real_phase_magnitude, fft_real_magnitude all deal with constructing a data set for inverse FFT.

To construct a data set for forward fft you should only need to convert your data set directly:

for(n...) { int_set[n].r = float_set[n].r * f; int_set[n].i = 0; } // f is for scaling if necessary
fft_fft(int_set, 10); // 10 for 1024

However, if you are converting real only data it is possible to optimize performance quite a bit by eliminating calculations for the rather useless mirror image of frequencies you will get from a regular FFT using an input set with no imaginary data:

for(n...) { int_set[n].r = float_set[n*2].r * f; int_set[n].i = float_set[n*2+1].r * f; }
fft_fftr(int_set, 9); // 9 for 512

I should have provided use cases and examples :D

You should however try to aquire the data in integer form instead of doing conversion for optimal performance.

**Comment by maximevince** [comment]
Ok, thanks for the explanation.
Now I understand why I didn't get the "fft_phase_magnitude, fft_magnitude, fft_real_dc, fft_real_phase_magnitude, fft_real_magnitude" functions, since they are meant for IFFT! :)

I am doing regular FFT (time-domain to frequency-domain) indeed.

The plan is to use integer-only (no conversion from float) on real input data, and indeed optimize by eliminating the mirror image. So indeed, using 512 "complex" samples as input, which are actually 1024 real values. Thanks for the info, it confirms the way of working I had foreseen, is indeed correct!

The reason I was starting from float and then converting is because the example provided by ARM is using 1024 float values, and I was using that as a control-set to see if the Cortex-M0 implementation was working correctly.

I might add an example to the repo when I am done.

**Comment by stg** [comment]
Thank you, and the best of luck!
Let me know if I can be of further assistance.

**Comment by maximevince** [comment]
Hey,
I have some more questions:
1) When converting the ARM example complex float dataset as suggested, I am getting odd results.
Convert complex float to complex int:
```for (n...) {        out[n].r = in[n*2+0]*scaling; out[n].i = in[n*2+1]*scaling; }```
Then ran:
```cmplx_float_to_int(f32in, input, FFT_SIZE, 1000);  fft_fft(input, 10); ```
Results in:
```[FFT] COMPLEX INPUT: maxIndex: 811 vs. refIndex: 213```
-> refIndex is supposed to be the most powerful frequency found (and the ouput found when using the ARM CMSIS FFT's)

2) Same thing for REAL dataset:
Convert complex float to real int:
```for (n...) {         out[n].r = (int32_t)(scaling * in[n*4 + 0]); out[n].i = (int32_t)(scaling * in[n*4 + 2]); }```
Then ran:
```cmplx_float_to_real_int(f32in, input, FFT_SIZE, 1000);  fft_fftr(input, 9); ```
Results in:
```[FFT] REAL INPUT: maxIndex: 426 vs. refIndex: 213```
-> refIndex is supposed to be the most powerful frequency found
-> The found maxIndex is *exactly 2x bigger* than the expected maxIndex. I guess this has to do with the way the results are translated from complex to real, or is it just a coincidence?

3) I ran a benchmark on 16 MHz Cortex-M0:
```
ARM Q31 COMPLEX FFT START
ARM Q31 COMPLEX FFT STOP (time: 65 ms)
ARM Q31 COMPLEX FFT FOUND MAX (time: 152 ms)
```

```
SYLT INT32 COMPLEX FFT START
SYLT INT32 COMPLEX FFT STOP (time: 89 ms)
SYLT INT32 COMPLEX FFT FOUND MAX (time: 175 ms)
```
So it seems the CMSIS library has a speed advantage here, but it's code size is significantly bigger:
ARM CMSIS code increase for complex Q31 FFT: 13292 bytes
SYLT-FFT code increate for complex INT32 FFT: 2692 bytes

**Comment by stg** [comment]
I am not surprised CMSIS is faster without DSP as the code is tighly optimized for specific cases and compilers but I am surprised the difference is so big but then again CMSIS may use more tables to speed things up. I currently have no hardware to test M0 targets.

I am not sure why you are getting half the value from this library as compared to CMSIS but I do not know the CMSIS implementation well. I did compare results from my library with several other open source implementations and found consistent results.

Output bin N corresponds to frequency sample_rate/fft_size*N meaning the first bin is DC (N=0). However, for an FFT done on real only data the second half of bins are a complex conjugate of the first (the mirror image one gets) meaning only the first half output bins contain useful information. This makes sense, as a real signal recorded at 48kHz could not possibly contain frequencies above 24kHz.

Using the real fft method instead should produce this first half only, in a dataset of half the size with improved performance.

It is difficult to give a better answer without looking at the code, but if you are able to share I wouldn't mind looking it over to try and produce a definite answer for you.

The dataset you sent documents the frequency (10kHz+noise) but it does not provide the sample rate so I can not do a verification.

**Comment by stg** [comment]
If the sample rate of that data set is 48kHz and the signal is 10kHz you should find the highest amplitude in bin 10000/(48000/1024) = 213, regardless of doing a complex FFT or a real FFT and regardless of what library you use. The only difference is the results of the real FFT will be half the size of the complex FFT since it does not contain the complex conjugate half.

**Comment by maximevince** [comment]
Hi @stg,
Thanks for the extra explanations.
I was misinterpreting the results:
I considered the output of the real-fft to be completely real-valued, and was also taking the complex output values from the results; hence why I got double the expected output index.
But the real-FFT is outputting 512 real+complex value pairs (contrarily to the complex FFT which would have given 1024 real+complex output pairs, including the mirror image (from index 512->1023) for a real input.
So looking at the 512 real output points only, this gives the correct results!

Great, thanks a lot!!

**Comment by maximevince** [comment]
Oh and by the way:
SYLT INT32 REAL FFT START (1024 samples)
SYLT INT32 REAL FFT STOP (time: 46 ms)
And only 1524 bytes flash memory used.
These are awesome numbers!

**Comment by stg** [comment]
Regarding "So looking at the 512 real output points only, this gives the correct results!"

In the FFT output, each complex bin (real + imaginary) describes a vector.
From this vector you can compute phase and magnitude.
Magnitude appears to be what you are looking for.

Thing is, if you look at the real bin only - a signal that is 90 or 270 degrees out of phase will show 0, while signals that are 0 or 180 degrees will show 0 in the imaginary part. When sampling real-world signals you will likely end up with the phase constantly changing over time.

To compute the magnitude you *must* do sqrt(r*r + i*i). That is the hypotenuse (or length) of the vector - while atan2(r, i) will give you the phase of that frequency bin. Skipping this step will give you highly inconsistent results.

Those new performance numbers do make me a much happier camper!

The large size of the ARM library was one of the key reasons for writing my own - I was working with a 32kB device so it just wouldn't fit until I manually broke out and deleted large quantities of constant data and while I was able to fit it - there was not much space left for anything else beyond my bootloader. The optimizations that came later was more of a "hmm... performance is actually pretty good... i wonder what happens if I..." moment, but one I am glad I had :)

We have one device that is producing realtime additive synthesized audio at 48kHz generated by IFFTR. It is a very close call, but I could not find another library that was able to cope with that sort of throughput and the only other solution would have been to upgrade the processor from 48 to 72 MHz - a much more expensive solution.

**Pull request merged**
